# this file is for aws codebuild

version: 0.2
phases:
  install:
    commands:
      - echo "Install Phase - Nothing to do using latest Amazon Linux Docker Image for CodeBuild which has all AWS Tools - https://github.com/aws/aws-codebuild-docker-images/blob/master/al2/x86_64/standard/3.0/Dockerfile"
  pre_build:
      commands:
        # Docker Image Tag with Date Time & Code Buiild Resolved Source Version (just create tag no build yet)
        - TAG="$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
        # Update Image tag in our Kubernetes Deployment Manifest (here is where i need to clone the infra repo)
        # in a prod app the repo is gonna be private so i will need to authenticate first
        # Login to ECR Registry for docker to push the image to ECR Repository
        - echo "Login in to Amazon ECR..."
        - $(aws ecr get-login --no-include-email)
        # Update Kube config Home Directory
        - export KUBECONFIG=$HOME/.kube/config
        # since this a share env using no login gives the tick rate problem
        - echo "Log in to Docker Hub..."
        - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  build:
    commands:
      # Build Docker Image
      - echo "Build started on `date`"
      - echo "Building the Docker image..."
      - ls
      - docker build --tag $FRONTEND:$TAG .
      - echo "Creating pull request from staging to main"
      - |
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -d '{"title": "Automated PR from staging to main", "head": "staging", "base": "main"}' \
          https://api.github.com/repos/$GIT_USER_NAME/$REPO_NAME/pulls
  post_build:
    commands:
      # Push Docker Image to ECR Repository
      - echo "Build completed on `date`"
      - echo "Pushing the Docker image to ECR Repository"
      - docker push $FRONTEND:$TAG
      - echo "Docker Image Push to ECR Completed -  $FRONTEND:$TAG"
      - git clone -b https://github.com/SalvadorM271/eks_terraform
      - cd eks_terraform/01_enviroments/stg/k8s_mern_alb_extDNS_autoscaler_aws_secrets        
      - echo "Update Image tag in kube-manifest..."
      - ls
      - sed -i 's@\(eks_mern_frontend:\).*@\1'"$TAG"'@' frontend_deployment.yml
      - cat frontend_deployment.yml
      - echo "pushing changes to infra repo..."
      # Verify AWS CLI Version        
      - echo "Verify AWS CLI Version..."
      - aws --version
      # values are in codebuild ENVs
      - git config --global user.email ${GIT_USER_EMAIL}
      - git config --global user.name ${GIT_USER_NAME}
      # apparenlly codepipeline does not give push permissions to codebuild so token was needed
      - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/eks_terraform.git
      - git add frontend_deployment.yml
      - git commit -m "Update frontend image tag to ${TAG}"
      - git push
      - echo "push to infra repo finish"    
      